version: '3'
services:
  message-receiver:
    image: tatsumibruno/message-receiver:0.0.1
    ports:
      - 8090:8080
    links:
      - rabbitmq
    networks:
      - messaging
  message-sender:
    image: tatsumibruno/message-sender:0.0.1
    ports:
      - 8080:8080
    links:
      - rabbitmq
    networks:
      - messaging
  rabbitmq:
    image: rabbitmq:3.7.17-alpine
    ports:
      - 5672:5672
    networks:
      - messaging
networks:
  messaging: